# Generated by Django 5.1.1 on 2024-09-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='post',
            name='artist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='designer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='genre_filter',
            field=models.CharField(choices=[('family', 'Family Game'), ('dexterity', 'Dexterity Game'), ('party', 'Party Game'), ('abstract', 'Abstract Game'), ('thematic', 'Thematic Game'), ('eurogame', 'Eurogame'), ('wargame', 'Wargame')], default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='max_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='min_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='solo_play',
            field=models.BooleanField(default=False),
        ),
    ]
