# Generated by Django 5.1.1 on 2024-09-25 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_content_remove_post_image_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre_filter',
            field=models.CharField(choices=[('none', 'none'), ('family', 'Family Game'), ('dexterity', 'Dexterity Game'), ('party', 'Party Game'), ('abstract', 'Abstract Game'), ('thematic', 'Thematic Game'), ('eurogame', 'Eurogame'), ('wargame', 'Wargame')], default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='min_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
