# Generated by Django 5.1.1 on 2024-09-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_game',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
