# Generated by Django 5.1.1 on 2024-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_content_profile_favourite_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default_profile_yqtpvj', upload_to='images/'),
        ),
    ]
