# Generated by Django 3.2.4 on 2024-10-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20241005_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre_filter',
            field=models.CharField(choices=[('none', 'none'), ('family', 'Family Game'), ('dexterity', 'Dexterity Game'), ('party', 'Party Game'), ('abstract', 'Abstract Game'), ('thematic', 'Thematic Game'), ('eurogame', 'Eurogame'), ('wargame', 'Wargame')], default='none', max_length=32),
        ),
    ]
