# Generated by Django 3.2.4 on 2024-10-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_genre_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_ynmksg', upload_to='images/'),
        ),
    ]
