# Generated by Django 5.1.1 on 2024-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_genre_filter_alter_post_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/default_post_ynmksg', upload_to='images/'),
        ),
    ]
